name: SG+US双区域-重建CF环境

on:
  workflow_dispatch:
    inputs:
      region:
        description: '选择操作区域'
        required: true
        default: 'SG'
        type: choice
        options:
          - SG  # 新加坡
          - US  # 美国
          - ALL # 新加坡+美国

jobs:
  # Job 1: SG 区域
  manage_cf_space_sg:
    name: 'SG - 检查、重建 CF 环境和创建空间'
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.inputs.region == 'SG' || github.event.inputs.region == 'ALL' }}
    
    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v4
      
    - name: 设置 Shell 脚本执行权限
      # 路径正确：./rebuild_cf_.sh
      run: chmod +x ./rebuild_cf_.sh 

    - name: 执行 SG 区域环境管理脚本
      env:
        # 环境变量名称正确
        CF_SPACE_SG: ${{ secrets.CF_SPACE_SG }}
        CF_ORG_SG: ${{ secrets.CF_ORG_SG }}
        BTP_ID_SG: ${{ secrets.BTP_ID_SG }}
        BTP_GLOBAL_API: ${{ secrets.BTP_GLOBAL_API }}
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        # 脚本调用和参数传递正确
        ./rebuild_cf_.sh \
          "SG" \
          "CF_SPACE_SG" \
          "CF_ORG_SG" \
          "BTP_ID_SG" \
          "${{ secrets.BTP_GLOBAL_API }}" \
          "${{ secrets.EMAIL }}" \
          "${{ secrets.PASSWORD }}"

  # Job 2: US 区域
  manage_cf_space_us:
    name: 'US - 检查、重建 CF 环境和创建空间'
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.inputs.region == 'US' || github.event.inputs.region == 'ALL' }}
    
    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v4
      
    - name: 设置 Shell 脚本执行权限
      # 路径正确：./rebuild_cf_.sh
      run: chmod +x ./rebuild_cf_.sh
      
    - name: 执行 US 区域环境管理脚本
      env:
        # 环境变量名称正确
        CF_SPACE_US: ${{ secrets.CF_SPACE_US }}
        CF_ORG_US: ${{ secrets.CF_ORG_US }}
        BTP_ID_US: ${{ secrets.BTP_ID_US }}
        BTP_GLOBAL_API: ${{ secrets.BTP_GLOBAL_API }}
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        # 脚本调用和参数传递正确
        ./rebuild_cf_.sh \
          "US" \
          "CF_SPACE_US" \
          "CF_ORG_US" \
          "BTP_ID_US" \
          "${{ secrets.BTP_GLOBAL_API }}" \
          "${{ secrets.EMAIL }}" \
          "${{ secrets.PASSWORD }}"
